spring:
  application:
    name: tech-challenge-delivery
  profiles:
    active: ${PROFILE:local}
application:
  jwt:
    expiration: ${JWT_EXPIRATION:600}
    public:
      key: ${JWT_PUBLIC_KEY:classpath:app.pub}
    private:
      key: ${JWT_PRIVATE_KEY:classpath:app.key}